import { z } from "zod/v4";
import type { RouteDoc } from "@/lib/docs/types";

// ─── Zod Schemas ─────────────────────────────────────────

export const TopProductSchema = z.object({
  id: z
    .number()
    .int()
    .min(1)
    .max(2147483647)
    .describe("Unique product identifier"),
  name: z.string().min(1).max(500).describe("Product display name"),
  revenue: z
    .number()
    .min(0)
    .max(999999999)
    .describe("Total revenue generated by this product in cents"),
  quantity: z
    .number()
    .int()
    .min(0)
    .max(999999999)
    .describe("Total quantity sold"),
});

export const TopProductsResponseSchema = z.object({
  products: z
    .array(TopProductSchema)
    .max(10)
    .describe("Top-selling products sorted by revenue descending"),
});

// ─── OpenAPI Route Doc ───────────────────────────────────

export const topProductsRouteDoc: RouteDoc = {
  path: "/api/admin/analytics/top-products",
  method: "get",
  scope: "internal",
  summary: "Get top-selling products",
  description:
    "Returns the top 10 products sorted by revenue in descending order. Each product includes its name, total revenue, and total quantity sold. Only products with at least one sale are included. Requires admin authentication.",
  tags: ["Admin", "Analytics"],
  security: [{ cookieAuth: [] }],
  responses: {
    "200": {
      description: "Top-selling products list",
      content: {
        "application/json": {
          schema: {
            type: "object",
            properties: {
              products: {
                type: "array",
                maxItems: 10,
                description:
                  "Top-selling products sorted by revenue descending",
                items: {
                  type: "object",
                  properties: {
                    id: {
                      type: "integer",
                      description: "Unique product identifier",
                      example: 3,
                    },
                    name: {
                      type: "string",
                      description: "Product display name",
                      example: "Premium Wireless Headphones",
                    },
                    revenue: {
                      type: "number",
                      description: "Total revenue in cents",
                      example: 450000,
                    },
                    quantity: {
                      type: "integer",
                      description: "Total quantity sold",
                      example: 150,
                    },
                  },
                },
              },
            },
          },
          example: {
            products: [
              {
                id: 3,
                name: "Premium Wireless Headphones",
                revenue: 450000,
                quantity: 150,
              },
              {
                id: 7,
                name: "Ergonomic Standing Desk",
                revenue: 320000,
                quantity: 40,
              },
              {
                id: 12,
                name: "Mechanical Keyboard",
                revenue: 195000,
                quantity: 130,
              },
            ],
          },
        },
      },
    },
    "403": {
      description: "Forbidden — user is not an admin",
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          example: { error: "Forbidden" },
        },
      },
    },
    "500": {
      description: "Internal server error",
      content: {
        "application/json": {
          schema: { $ref: "#/components/schemas/Error" },
          example: { error: "Failed to load top products" },
        },
      },
    },
  },
};
